title: Grav
author:
  name: Jane Bloggs
  email: 'jane@test.com'
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
gitrepo:
  editlinkicon: github
  editlinktext: 'View Markdown for this Page'
  edittreeurl: https://raw.githubusercontent.com/hibbitts-design/grav-skeleton-workshop-demo-site/master/user
  viewtreetext: Explore this site's User folder
  viewtreeurl: https://github.com/hibbitts-design/grav-skeleton-workshop-demo-site/tree/master/user
gitrepouser:
  viewfoldericon: github
  viewfoldertext: Explore this Skeleton's User folder
  viewfolderurl: https://github.com/hibbitts-design/grav-skeleton-workshop-demo-site/tree/master/user
